### ISSUE TITLE
do you test  it？

### ISSUE THREAD

**Issue by xiaocainiaooo** [zhongjhATC/Retrofit2Rxjava2Download#2]
Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
        at android.os.BaseBundle.getInt(BaseBundle.java:1045)
        at android.os.BaseBundle.getInt(BaseBundle.java:1027)
        at com.zhongjh.retrofitdownloadlib.http.DownloadHandler$1.handleMessage(DownloadHandler.java:46)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by zhongjhATC** [comment]
1.01版本已修复
